### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by InterstellarIntruder** [rgl-epfl/differentiable-sdf-rendering#15]
I am working on a windows system with an RTX graphics card. 

```
D:\github\differentiable-sdf-rendering\python>python optimize.py dragon --optconfig no-tex-12
Traceback (most recent call last):
  File "D:\github\differentiable-sdf-rendering\python\optimize.py", line 108, in <module>
    main(sys.argv[1:])
  File "D:\github\differentiable-sdf-rendering\python\optimize.py", line 80, in main
    from configs import apply_cmdline_args, get_config
  File "D:\github\differentiable-sdf-rendering\python\configs.py", line 4, in <module>
    import integrators.sdf_silhouette_reparam
  File "D:\github\differentiable-sdf-rendering\python\integrators\sdf_silhouette_reparam.py", line 4, in <module>
    from .reparam import ReparamIntegrator
  File "D:\github\differentiable-sdf-rendering\python\integrators\reparam.py", line 6, in <module>
    from shapes import Grid3d
  File "D:\github\differentiable-sdf-rendering\python\shapes.py", line 6, in <module>
    import redistancing
  File "D:\github\differentiable-sdf-rendering\python\redistancing.py", line 1, in <module>
    import fastsweep
  File "C:\Users\franc\anaconda3\lib\site-packages\fastsweep\__init__.py", line 3, in <module>
    from ._fastsweep_core import __doc__, __version__
ImportError: DLL load failed while importing _fastsweep_core: The specified procedure could not be found.
```

There seems to be an issue with fastsweep. Has anyone run into this?

**Comment by InterstellarIntruder** [comment]
On an ubuntu system, I get this error.

Any advice would be helpful

```
 python3 optimize.py dragon --optconfig no-tex-12Traceback (most recent call last):
  File "optimize.py", line 108, in <module>
    main(sys.argv[1:])
  File "optimize.py", line 80, in main
    from configs import apply_cmdline_args, get_config
  File "/home/paperspace/diff_render/differentiable-sdf-rendering/python/configs.py", line 4, in <module>
    import integrators.sdf_silhouette_reparam
  File "/home/paperspace/diff_render/differentiable-sdf-rendering/python/integrators/sdf_silhouette_reparam.py", line 4, in <module>
    from .reparam import ReparamIntegrator
  File "/home/paperspace/diff_render/differentiable-sdf-rendering/python/integrators/reparam.py", line 6, in <module>
    from shapes import Grid3d
  File "/home/paperspace/diff_render/differentiable-sdf-rendering/python/shapes.py", line 6, in <module>
    import redistancing
  File "/home/paperspace/diff_render/differentiable-sdf-rendering/python/redistancing.py", line 1, in <module>
    import fastsweep
  File "/home/paperspace/.local/lib/python3.8/site-packages/fastsweep/__init__.py", line 3, in <module>
    from ._fastsweep_core import __doc__, __version__
ImportError: /home/paperspace/.local/lib/python3.8/site-packages/fastsweep/_fastsweep_core.cpython-38-x86_64-linux-gnu.so: undefined symbol: jit_var_new_scatter
```

**Comment by dvicini** [comment]
Sorry about that, I finally upgraded the fastsweep package to be compatible with the latest mitsuba/drjit
