### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by IcyChlorine** [rgl-epfl/differentiable-sdf-rendering#18]
## Problem
When I try to run the command 
```
python python/optimize.py dragon --optconfig no-tex-12
```
An error occurred and the traceback message is:
```
lcj20@LAPTOP-I18D84IU MINGW64 /c/StarSky/Garage/blender_lab/sdf三维重建/differentiable-sdf-rendering (main)
$ python python/optimize.py dragon --optconfig no-tex-12
C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\scenes\dragon\dragon.xml sdf_direct_reparam 2048 128 128
Traceback (most recent call last):
  File "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\python\optimize.py", line 109, in <module>
    main(sys.argv[1:])
  File "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\python\optimize.py", line 105, in main
    optimize(scene_name, config, opt_config, args.outputdir, args.refspp, args.force, args.verbose, remaining_args)
  File "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\python\optimize.py", line 57, in optimize
    render_reference_images(opt_config, config, ref_spp=ref_spp, force=force, verbose=verbose, mts_args=mts_args)
  File "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\python\optimize.py", line 18, in render_reference_images  
    ref_scene = mi.load_file(ref_scene_name, integrator=config.integrator, spp=ref_spp,
RuntimeError: ​[xml.cpp:1119] Error while loading "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\scenes\dragon\.
.\emitters\cathedral.xml" (near line 2, col 3): could not instantiate emitter plugin of type "envmap":
[xml.cpp:1119]   [FileStream] "C:\StarSky\Garage\blender_lab\sdf三维重建\differentiable-sdf-rendering\scenes\dragon\..\textures\cathedral.hdr": I/O error while attempting to open file: No such file or directory
```
What's wrong and what can I do?

## Environment
Win 10
(anaconda)Python 3.10.9

## Possible reason?
I've downloaded the scene files and extracted them as `..\differentiable-sdf-rendering\scenes\...` and I've installed the required packages via pip.
After examining the codes and the `.xml` configuration files, I suspect `mitsubi` is unable to recognize the relative path properly, which are specified in xml files.

I'll appreciate any discussions and guidance! QAQ

**Comment by zichenwang01** [comment]
Try cd to the python folder first

**Comment by IcyChlorine** [comment]
Thank you, it worked!
Never expected the issue is caused by cwd path T_T
